/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import javax.swing.SpinnerNumberModel;
import scopelite.ScopeLite;

/**
 *
 * @author SHOTbyGUN
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        setTitle("Scope settings");
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        colorDialog = new javax.swing.JDialog();
        barColorChooser = new javax.swing.JColorChooser();
        jSplitPane5 = new javax.swing.JSplitPane();
        colorDialogOk = new javax.swing.JButton();
        colorDialogCancel = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        soundDeviceSelection = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jLabel2 = new javax.swing.JLabel();
        barAmount = new javax.swing.JSpinner();
        jSplitPane3 = new javax.swing.JSplitPane();
        jSplitPane4 = new javax.swing.JSplitPane();
        jLabel3 = new javax.swing.JLabel();
        viewBarColor = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        colorDialogOk.setText("  OK  ");
        colorDialogOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorDialogOkActionPerformed(evt);
            }
        });
        jSplitPane5.setLeftComponent(colorDialogOk);

        colorDialogCancel.setText("CANCEL");
        colorDialogCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorDialogCancelActionPerformed(evt);
            }
        });
        jSplitPane5.setRightComponent(colorDialogCancel);

        javax.swing.GroupLayout colorDialogLayout = new javax.swing.GroupLayout(colorDialog.getContentPane());
        colorDialog.getContentPane().setLayout(colorDialogLayout);
        colorDialogLayout.setHorizontalGroup(
            colorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(barColorChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        colorDialogLayout.setVerticalGroup(
            colorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorDialogLayout.createSequentialGroup()
                .addComponent(barColorChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSplitPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(getFont());
        jLabel1.setText("  Sound device  ");
        jSplitPane1.setLeftComponent(jLabel1);

        soundDeviceSelection.setFont(getFont());
        soundDeviceSelection.setModel(new javax.swing.AbstractListModel() {
            String[] strings = new String[scopelite.ScopeLite.soundCapturer.mixers.size()];
            {
                for(int i = 0; i < scopelite.ScopeLite.soundCapturer.mixers.size(); i++) {
                    strings[i] = scopelite.ScopeLite.soundCapturer.mixers.get(i).getName();
                };
            }
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        soundDeviceSelection.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        soundDeviceSelection.setSelectedIndex(scopelite.ScopeLite.soundCapturer.currentMixer);
        soundDeviceSelection.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                soundDeviceSelectionValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(soundDeviceSelection);

        jSplitPane1.setRightComponent(jScrollPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(243, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("System", jPanel1);

        jLabel2.setFont(getFont());
        jLabel2.setText("  Bar amount  ");
        jSplitPane2.setLeftComponent(jLabel2);

        barAmount.setFont(getFont());
        barAmount.setModel(new javax.swing.SpinnerNumberModel());
        barAmount.setValue(scopelite.ScopeLite.drawer.getBarAmount());
        barAmount.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                barAmountStateChanged(evt);
            }
        });
        jSplitPane2.setRightComponent(barAmount);

        jLabel3.setFont(getFont());
        jLabel3.setText("  Bar color  ");
        jSplitPane4.setLeftComponent(jLabel3);

        viewBarColor.setBackground(scopelite.ScopeLite.drawer.getBarColor());
        viewBarColor.setMinimumSize(new java.awt.Dimension(10, 10));
        viewBarColor.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout viewBarColorLayout = new javax.swing.GroupLayout(viewBarColor);
        viewBarColor.setLayout(viewBarColorLayout);
        viewBarColorLayout.setHorizontalGroup(
            viewBarColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        viewBarColorLayout.setVerticalGroup(
            viewBarColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jSplitPane4.setRightComponent(viewBarColor);

        jSplitPane3.setLeftComponent(jSplitPane4);

        jButton1.setText("Change");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jSplitPane3.setRightComponent(jButton1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSplitPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSplitPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(392, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(316, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Bars", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void soundDeviceSelectionValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_soundDeviceSelectionValueChanged
        // TODO add your handling code here:
        scopelite.ScopeLite.soundCapturer.currentMixer = soundDeviceSelection.getSelectedIndex();
        scopelite.ScopeLite.soundCapturer.restart();
    }//GEN-LAST:event_soundDeviceSelectionValueChanged

    private void barAmountStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_barAmountStateChanged
        // TODO add your handling code here:
        scopelite.ScopeLite.drawer.modifyBar(0, 
                ((SpinnerNumberModel)barAmount.getModel()).getNumber().intValue() 
                - scopelite.ScopeLite.drawer.getBarAmount());
    }//GEN-LAST:event_barAmountStateChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        ScopeLite.scopeLite.gui = null;
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void colorDialogCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorDialogCancelActionPerformed
        // TODO add your handling code here:
        colorDialog.dispose();
    }//GEN-LAST:event_colorDialogCancelActionPerformed

    private void colorDialogOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorDialogOkActionPerformed
        // TODO add your handling code here:
        scopelite.ScopeLite.drawer.setBarColor(barColorChooser.getColor());
        viewBarColor.setBackground(scopelite.ScopeLite.drawer.getBarColor());
        colorDialog.dispose();
    }//GEN-LAST:event_colorDialogOkActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner barAmount;
    private javax.swing.JColorChooser barColorChooser;
    private javax.swing.JDialog colorDialog;
    private javax.swing.JButton colorDialogCancel;
    private javax.swing.JButton colorDialogOk;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JSplitPane jSplitPane4;
    private javax.swing.JSplitPane jSplitPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList soundDeviceSelection;
    private javax.swing.JPanel viewBarColor;
    // End of variables declaration//GEN-END:variables
}
